import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="theme-color-1">
                {children}
                <Script
                    src="https://kit.fontawesome.com/36dd0428ff.js"
                    crossorigin="anonymous"
                ></Script>
                <Script src="../assets/scripts/script.js"></Script>
            </body>
        </html>
    );
}
